### ISSUE TITLE
Get hostdata folder using ctrl_options

### ISSUE THREAD

**Issue by TGates71** [apintocr/sentora_mail-quota-count#1]
(Will need testing, writing from my poor memory lol.)
This will get the hostdata path from system settings: (Allows use on Windows)
Change line 111 hooksCtrl.php:

``` php
global $zdbh;
```

To:

``` php
global $zdbh, $controller;
```

Change line 119 hooksCtrl.php:

``` php
$hd_path   = "/var/sentora/hostdata"; // Path to hostdata
```

To:

``` php
$hd_path   = ctrl_options::GetOption('hosted_dir'); // Path to hostdata
```

**Comment by apintocr** [comment]
Good memory :)
Right Paths :+1: 
Done, thank you @TGates71
